at first we are import 3 or (how many you want) sentences

In [16]:
Sport = ''' The teams growth this season had a huge impact, helping them break a historic record, and this record will likely impact the future growth of the club '''

In [17]:
Economy = ''' The country’s economic growth reached a record level this year, and this record growth is expected to have a strong impact on investment, employment, and long‑term economic growth '''

In [18]:
News = ''' The report highlighted the rapid growth of renewable energy, reaching a record level this year, and this record growth could have a major global impact on climate policy and future energy growth '''

In [19]:
document = [Sport , Economy , News]
label = ['sport' , 'economy' , 'news']

In [20]:
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer

In [21]:
vectorizer = CountVectorizer()
vec_data = vectorizer.fit_transform(document)

In [22]:
vec_data

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 63 stored elements and shape (3, 45)>

In [23]:
vec_data_array = vec_data.toarray()

In [24]:
vec_data_array

array([[1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 2, 1, 0, 1, 0, 1, 1, 2, 0, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 1, 0, 3, 1, 2, 0, 1,
        0],
       [2, 0, 0, 0, 0, 1, 2, 1, 0, 1, 0, 0, 3, 0, 1, 0, 0, 0, 0, 1, 1, 1,
        1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 2, 0, 0, 0, 1, 0, 1, 1, 0, 2, 1, 0,
        1],
       [2, 0, 1, 0, 1, 0, 0, 0, 2, 0, 1, 1, 3, 0, 1, 0, 1, 0, 0, 1, 0, 0,
        1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 2, 1, 1, 0, 0, 0, 0, 2, 0, 2, 0, 0,
        1]], dtype=int64)

In [25]:
features = vectorizer.get_feature_names_out()

In [26]:
features

array(['and', 'break', 'climate', 'club', 'could', 'country', 'economic',
       'employment', 'energy', 'expected', 'future', 'global', 'growth',
       'had', 'have', 'helping', 'highlighted', 'historic', 'huge',
       'impact', 'investment', 'is', 'level', 'likely', 'long', 'major',
       'of', 'on', 'policy', 'rapid', 'reached', 'reaching', 'record',
       'renewable', 'report', 'season', 'strong', 'teams', 'term', 'the',
       'them', 'this', 'to', 'will', 'year'], dtype=object)

In [27]:
import pandas as pd

In [29]:
whole_data = pd.DataFrame(vec_data_array , columns=features)

In [30]:
whole_data.shape

(3, 45)

In [31]:
whole_data

   and  break  climate  club  could  country  ...  the  them  this  to  will  year
0    1      1        0     1      0        0  ...    3     1     2   0     1     0
1    2      0        0     0      0        1  ...    1     0     2   1     0     1
2    2      0        1     0      1        0  ...    2     0     2   0     0     1

[3 rows x 45 columns]

In [32]:
Tf_vectorizer = TfidfVectorizer()
data_Tf = Tf_vectorizer.fit_transform(document)

In [33]:
data_Tf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 63 stored elements and shape (3, 45)>

In [34]:
data_Tf_array = data_Tf.toarray()

In [36]:
data_Tf_array

array([[0.1281941 , 0.21705147, 0.        , 0.21705147, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.16507324, 0.        , 0.25638819, 0.21705147, 0.        ,
        0.21705147, 0.        , 0.21705147, 0.21705147, 0.25638819,
        0.        , 0.        , 0.        , 0.21705147, 0.        ,
        0.        , 0.16507324, 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.25638819, 0.        , 0.        ,
        0.21705147, 0.        , 0.21705147, 0.        , 0.38458229,
        0.21705147, 0.25638819, 0.        , 0.21705147, 0.        ],
       [0.23944462, 0.        , 0.        , 0.        , 0.        ,
        0.20270749, 0.40541498, 0.20270749, 0.        , 0.20270749,
        0.        , 0.        , 0.35916693, 0.        , 0.15416427,
        0.        , 0.        , 0.        , 0.        , 0.11972231,
        0.20270749, 0.20270749, 0.15416427, 0.        , 0.20270749,
        0.        , 0.        , 0.15416427, 0.        , 0.        ,
        0.20270749, 0.        , 0.23944462, 0.        , 0.        ,
        0.        , 0.20270749, 0.        , 0.20270749, 0.11972231,
        0.        , 0.23944462, 0.20270749, 0.        , 0.15416427],
       [0.22929024, 0.        , 0.19411106, 0.        , 0.19411106,
        0.        , 0.        , 0.        , 0.38822212, 0.        ,
        0.14762647, 0.19411106, 0.34393536, 0.        , 0.14762647,
        0.        , 0.19411106, 0.        , 0.        , 0.11464512,
        0.        , 0.        , 0.14762647, 0.        , 0.        ,
        0.19411106, 0.14762647, 0.14762647, 0.19411106, 0.19411106,
        0.        , 0.19411106, 0.22929024, 0.19411106, 0.19411106,
        0.        , 0.        , 0.        , 0.        , 0.22929024,
        0.        , 0.22929024, 0.        , 0.        , 0.14762647]])

In [37]:
features_Tf = Tf_vectorizer.get_feature_names_out()

In [38]:
features_Tf

array(['and', 'break', 'climate', 'club', 'could', 'country', 'economic',
       'employment', 'energy', 'expected', 'future', 'global', 'growth',
       'had', 'have', 'helping', 'highlighted', 'historic', 'huge',
       'impact', 'investment', 'is', 'level', 'likely', 'long', 'major',
       'of', 'on', 'policy', 'rapid', 'reached', 'reaching', 'record',
       'renewable', 'report', 'season', 'strong', 'teams', 'term', 'the',
       'them', 'this', 'to', 'will', 'year'], dtype=object)

In [39]:
whole_data_Tf = pd.DataFrame(data_Tf_array , columns=features_Tf)

In [40]:
whole_data_Tf

        and     break   climate  ...        to      will      year
0  0.128194  0.217051  0.000000  ...  0.000000  0.217051  0.000000
1  0.239445  0.000000  0.000000  ...  0.202707  0.000000  0.154164
2  0.229290  0.000000  0.194111  ...  0.000000  0.000000  0.147626

[3 rows x 45 columns]

As you see Tf_vectorizer normalized the dataset

In [41]:
whole_data_Tf.shape

(3, 45)