A dataset from concrete_compressive_strength for regression the values.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import Dense,Dropout,Flatten

In [2]:
data = pd.read_csv("D:\\python-venv\\NN_resg\\Data\\concrete_data.csv")

In [3]:
data.head()

,cement,blast_furnace_slag,fly_ash,water,superplasticizer,coarse_aggregate,fine_aggregate,age,concrete_compressive_strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [4]:
data.isna().sum()

cement                           0
blast_furnace_slag               0
fly_ash                          0
water                            0
superplasticizer                 0
coarse_aggregate                 0
fine_aggregate                   0
age                              0
concrete_compressive_strength    0
dtype: int64

In [5]:
data[data.age == 0]

Empty DataFrame
Columns: [cement, blast_furnace_slag, fly_ash, water, superplasticizer, coarse_aggregate, fine_aggregate , age, concrete_compressive_strength]
Index: []

In [6]:
X = data.drop(['concrete_compressive_strength'] ,axis=1)
y = data['concrete_compressive_strength']

In [7]:
y.shape

(1030,)

In [8]:
X.shape

(1030, 8)

In [9]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

In [10]:
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

In [11]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.3)

activation func and units changed than fashion_mnist because of that its regressoin and has just one output but in f_m was a classification problem with 10 classes.

In [19]:
# model
model = tf.keras.models.Sequential()
model.add(Dense(units=256 , activation='relu' , input_shape = (8,)))
model.add(Dropout(0.3))
model.add(Dense(units=256 , activation='relu'))
model.add(Dense(units=1 , activation='linear'))

In [15]:
# model_compiling
opt = tf.keras.optimizers.Adam(learning_rate=0.01)
loss = tf.keras.losses.MeanAbsoluteError()
model.compile(optimizer= opt , loss= loss)

In [16]:
# model_fitting
model.fit(X_train , y_train , epochs= 200 , batch_size= 50 , verbose= 2 , validation_data=(X_test , y_test))

Epoch 1/200
15/15 - 1s - 43ms/step - loss: 19.8397 - val_loss: 15.0021
Epoch 2/200
15/15 - 0s - 6ms/step - loss: 10.9285 - val_loss: 10.9538
Epoch 3/200
15/15 - 0s - 6ms/step - loss: 9.0791 - val_loss: 9.5453
Epoch 4/200
15/15 - 0s - 6ms/step - loss: 8.6687 - val_loss: 9.9024
Epoch 5/200
15/15 - 0s - 12ms/step - loss: 8.7024 - val_loss: 9.7621
Epoch 6/200
15/15 - 0s - 7ms/step - loss: 8.3691 - val_loss: 9.6980
Epoch 7/200
15/15 - 0s - 6ms/step - loss: 8.2223 - val_loss: 9.5773
Epoch 8/200
15/15 - 0s - 6ms/step - loss: 8.1493 - val_loss: 9.2516
Epoch 9/200
15/15 - 0s - 6ms/step - loss: 8.0703 - val_loss: 8.9821
Epoch 10/200
15/15 - 0s - 6ms/step - loss: 8.1722 - val_loss: 9.2589
Epoch 11/200
15/15 - 0s - 6ms/step - loss: 7.6617 - val_loss: 8.6479
Epoch 12/200
15/15 - 0s - 6ms/step - loss: 7.4243 - val_loss: 8.0701
Epoch 13/200
15/15 - 0s - 6ms/step - loss: 7.0799 - val_loss: 7.8574
Epoch 14/200
15/15 - 0s - 6ms/step - loss: 7.0769 - val_loss: 7.5677
Epoch 15/200
15/15 - 0s - 8ms/step - loss: 6.8835 - val_loss: 7.2685
Epoch 16/200
15/15 - 0s - 6ms/step - loss: 6.6990 - val_loss: 6.9014
Epoch 17/200
15/15 - 0s - 6ms/step - loss: 6.7016 - val_loss: 6.7616
Epoch 18/200
15/15 - 0s - 6ms/step - loss: 6.3835 - val_loss: 6.6887
Epoch 19/200
15/15 - 0s - 6ms/step - loss: 6.7199 - val_loss: 7.0353
Epoch 20/200
15/15 - 0s - 6ms/step - loss: 6.6188 - val_loss: 6.8013
Epoch 21/200
15/15 - 0s - 6ms/step - loss: 6.5697 - val_loss: 6.3454
Epoch 22/200
15/15 - 0s - 6ms/step - loss: 6.5028 - val_loss: 7.9242
Epoch 23/200
15/15 - 0s - 6ms/step - loss: 6.2260 - val_loss: 6.3440
Epoch 24/200
15/15 - 0s - 6ms/step - loss: 6.5369 - val_loss: 6.5860
Epoch 25/200
15/15 - 0s - 6ms/step - loss: 6.0833 - val_loss: 6.0996
Epoch 26/200
15/15 - 0s - 6ms/step - loss: 6.4197 - val_loss: 7.9188
Epoch 27/200
15/15 - 0s - 6ms/step - loss: 6.7528 - val_loss: 6.0418
Epoch 28/200
15/15 - 0s - 6ms/step - loss: 6.0082 - val_loss: 6.3017
Epoch 29/200
15/15 - 0s - 6ms/step - loss: 5.8255 - val_loss: 5.8681
Epoch 30/200
15/15 - 0s - 6ms/step - loss: 5.9648 - val_loss: 5.8091
Epoch 31/200
15/15 - 0s - 6ms/step - loss: 5.9301 - val_loss: 6.4978
Epoch 32/200
15/15 - 0s - 6ms/step - loss: 5.8897 - val_loss: 5.6138
Epoch 33/200
15/15 - 0s - 6ms/step - loss: 5.6605 - val_loss: 6.0010
Epoch 34/200
15/15 - 0s - 6ms/step - loss: 5.9417 - val_loss: 5.7320
Epoch 35/200
15/15 - 0s - 6ms/step - loss: 5.5699 - val_loss: 5.5706
Epoch 36/200
15/15 - 0s - 6ms/step - loss: 5.7639 - val_loss: 5.8353
Epoch 37/200
15/15 - 0s - 6ms/step - loss: 5.4914 - val_loss: 5.4714
Epoch 38/200
15/15 - 0s - 6ms/step - loss: 5.7422 - val_loss: 5.9253
Epoch 39/200
15/15 - 0s - 6ms/step - loss: 5.4887 - val_loss: 5.5006
Epoch 40/200
15/15 - 0s - 6ms/step - loss: 5.4241 - val_loss: 6.0289
Epoch 41/200
15/15 - 0s - 6ms/step - loss: 5.3781 - val_loss: 5.7974
Epoch 42/200
15/15 - 0s - 6ms/step - loss: 5.8010 - val_loss: 5.4278
Epoch 43/200
15/15 - 0s - 6ms/step - loss: 5.3686 - val_loss: 5.6149
Epoch 44/200
15/15 - 0s - 6ms/step - loss: 5.5485 - val_loss: 5.5696
Epoch 45/200
15/15 - 0s - 6ms/step - loss: 5.4569 - val_loss: 5.7087
Epoch 46/200
15/15 - 0s - 6ms/step - loss: 5.6640 - val_loss: 5.6918
Epoch 47/200
15/15 - 0s - 6ms/step - loss: 5.6085 - val_loss: 5.3863
Epoch 48/200
15/15 - 0s - 6ms/step - loss: 5.4247 - val_loss: 5.4688
Epoch 49/200
15/15 - 0s - 6ms/step - loss: 5.5360 - val_loss: 5.3989
Epoch 50/200
15/15 - 0s - 6ms/step - loss: 5.2021 - val_loss: 5.4890
Epoch 51/200
15/15 - 0s - 6ms/step - loss: 5.2599 - val_loss: 5.4017
Epoch 52/200
15/15 - 0s - 6ms/step - loss: 5.2421 - val_loss: 5.2834
Epoch 53/200
15/15 - 0s - 6ms/step - loss: 5.8278 - val_loss: 5.3737
Epoch 54/200
15/15 - 0s - 6ms/step - loss: 5.2812 - val_loss: 5.1598
Epoch 55/200
15/15 - 0s - 6ms/step - loss: 5.6790 - val_loss: 5.1880
Epoch 56/200
15/15 - 0s - 7ms/step - loss: 5.4495 - val_loss: 5.2332
Epoch 57/200
15/15 - 0s - 6ms/step - loss: 5.3335 - val_loss: 5.7229
Epoch 58/200
15/15 - 0s - 6ms/step - loss: 5.1157 - val_loss: 5.1200
Epoch 59/200
15/15 - 0s - 6ms/step - loss: 5.2917 - val_loss: 5.2297
Epoch 60/200
15/15 - 0s - 6ms/step - loss: 5.5182 - val_loss: 5.1607
Epoch 61/200
15/15 - 0s - 6ms/step - loss: 5.2577 - val_loss: 6.6472
Epoch 62/200
15/15 - 0s - 6ms/step - loss: 5.8127 - val_loss: 5.0804
Epoch 63/200
15/15 - 0s - 6ms/step - loss: 5.2067 - val_loss: 5.1566
Epoch 64/200
15/15 - 0s - 6ms/step - loss: 5.3491 - val_loss: 5.5918
Epoch 65/200
15/15 - 0s - 6ms/step - loss: 5.3271 - val_loss: 5.0500
Epoch 66/200
15/15 - 0s - 6ms/step - loss: 5.0929 - val_loss: 5.3269
Epoch 67/200
15/15 - 0s - 6ms/step - loss: 5.0467 - val_loss: 4.9292
Epoch 68/200
15/15 - 0s - 6ms/step - loss: 5.1098 - val_loss: 5.1443
Epoch 69/200
15/15 - 0s - 6ms/step - loss: 5.4721 - val_loss: 6.2138
Epoch 70/200
15/15 - 0s - 6ms/step - loss: 5.8432 - val_loss: 6.2657
Epoch 71/200
15/15 - 0s - 6ms/step - loss: 5.5576 - val_loss: 5.3134
Epoch 72/200
15/15 - 0s - 6ms/step - loss: 5.2394 - val_loss: 5.1649
Epoch 73/200
15/15 - 0s - 6ms/step - loss: 5.1566 - val_loss: 5.4754
Epoch 74/200
15/15 - 0s - 6ms/step - loss: 5.6758 - val_loss: 6.4284
Epoch 75/200
15/15 - 0s - 6ms/step - loss: 5.2402 - val_loss: 5.2390
Epoch 76/200
15/15 - 0s - 6ms/step - loss: 4.9466 - val_loss: 6.2425
Epoch 77/200
15/15 - 0s - 6ms/step - loss: 5.7253 - val_loss: 5.4134
Epoch 78/200
15/15 - 0s - 6ms/step - loss: 5.6878 - val_loss: 6.8596
Epoch 79/200
15/15 - 0s - 6ms/step - loss: 5.4256 - val_loss: 5.2572
Epoch 80/200
15/15 - 0s - 6ms/step - loss: 5.2505 - val_loss: 5.1422
Epoch 81/200
15/15 - 0s - 6ms/step - loss: 5.6657 - val_loss: 5.0080
Epoch 82/200
15/15 - 0s - 6ms/step - loss: 4.9800 - val_loss: 5.1899
Epoch 83/200
15/15 - 0s - 6ms/step - loss: 5.1578 - val_loss: 5.0738
Epoch 84/200
15/15 - 0s - 6ms/step - loss: 5.0546 - val_loss: 4.9677
Epoch 85/200
15/15 - 0s - 6ms/step - loss: 5.0610 - val_loss: 4.9118
Epoch 86/200
15/15 - 0s - 6ms/step - loss: 4.9324 - val_loss: 5.1996
Epoch 87/200
15/15 - 0s - 6ms/step - loss: 4.9628 - val_loss: 5.0299
Epoch 88/200
15/15 - 0s - 6ms/step - loss: 5.1635 - val_loss: 6.1027
Epoch 89/200
15/15 - 0s - 12ms/step - loss: 5.2845 - val_loss: 5.5523
Epoch 90/200
15/15 - 0s - 6ms/step - loss: 4.9602 - val_loss: 5.2182
Epoch 91/200
15/15 - 0s - 6ms/step - loss: 5.2317 - val_loss: 5.2685
Epoch 92/200
15/15 - 0s - 6ms/step - loss: 5.0831 - val_loss: 5.0230
Epoch 93/200
15/15 - 0s - 6ms/step - loss: 5.0397 - val_loss: 5.6212
Epoch 94/200
15/15 - 0s - 6ms/step - loss: 5.6430 - val_loss: 5.7685
Epoch 95/200
15/15 - 0s - 6ms/step - loss: 5.0162 - val_loss: 4.9844
Epoch 96/200
15/15 - 0s - 6ms/step - loss: 4.9696 - val_loss: 5.8270
Epoch 97/200
15/15 - 0s - 6ms/step - loss: 5.4621 - val_loss: 5.9637
Epoch 98/200
15/15 - 0s - 6ms/step - loss: 4.9990 - val_loss: 5.2456
Epoch 99/200
15/15 - 0s - 6ms/step - loss: 4.9705 - val_loss: 5.0972
Epoch 100/200
15/15 - 0s - 6ms/step - loss: 4.9710 - val_loss: 4.9047
Epoch 101/200
15/15 - 0s - 6ms/step - loss: 5.0897 - val_loss: 6.3429
Epoch 102/200
15/15 - 0s - 6ms/step - loss: 5.3608 - val_loss: 5.7779
Epoch 103/200
15/15 - 0s - 6ms/step - loss: 4.9519 - val_loss: 5.1413
Epoch 104/200
15/15 - 0s - 6ms/step - loss: 4.9636 - val_loss: 5.1384
Epoch 105/200
15/15 - 0s - 6ms/step - loss: 4.8495 - val_loss: 5.5543
Epoch 106/200
15/15 - 0s - 6ms/step - loss: 4.7540 - val_loss: 4.9483
Epoch 107/200
15/15 - 0s - 6ms/step - loss: 5.1892 - val_loss: 5.2139
Epoch 108/200
15/15 - 0s - 6ms/step - loss: 4.7318 - val_loss: 4.9251
Epoch 109/200
15/15 - 0s - 6ms/step - loss: 4.5714 - val_loss: 4.8964
Epoch 110/200
15/15 - 0s - 6ms/step - loss: 4.7206 - val_loss: 5.1711
Epoch 111/200
15/15 - 0s - 6ms/step - loss: 4.8873 - val_loss: 4.9705
Epoch 112/200
15/15 - 0s - 7ms/step - loss: 4.7171 - val_loss: 4.9756
Epoch 113/200
15/15 - 0s - 6ms/step - loss: 5.0477 - val_loss: 4.9763
Epoch 114/200
15/15 - 0s - 6ms/step - loss: 4.8565 - val_loss: 5.2330
Epoch 115/200
15/15 - 0s - 6ms/step - loss: 5.0220 - val_loss: 5.0064
Epoch 116/200
15/15 - 0s - 6ms/step - loss: 4.9762 - val_loss: 5.3250
Epoch 117/200
15/15 - 0s - 6ms/step - loss: 4.6466 - val_loss: 5.0020
Epoch 118/200
15/15 - 0s - 6ms/step - loss: 4.6328 - val_loss: 4.9471
Epoch 119/200
15/15 - 0s - 6ms/step - loss: 4.7041 - val_loss: 5.1523
Epoch 120/200
15/15 - 0s - 6ms/step - loss: 4.8660 - val_loss: 4.7564
Epoch 121/200
15/15 - 0s - 6ms/step - loss: 4.5112 - val_loss: 5.1706
Epoch 122/200
15/15 - 0s - 8ms/step - loss: 4.6581 - val_loss: 6.7442
Epoch 123/200
15/15 - 0s - 6ms/step - loss: 5.4242 - val_loss: 5.8374
Epoch 124/200
15/15 - 0s - 6ms/step - loss: 4.9555 - val_loss: 4.9578
Epoch 125/200
15/15 - 0s - 5ms/step - loss: 4.5832 - val_loss: 5.6187
Epoch 126/200
15/15 - 0s - 6ms/step - loss: 4.8282 - val_loss: 5.0943
Epoch 127/200
15/15 - 0s - 6ms/step - loss: 5.3354 - val_loss: 5.4819
Epoch 128/200
15/15 - 0s - 6ms/step - loss: 4.6845 - val_loss: 4.8592
Epoch 129/200
15/15 - 0s - 6ms/step - loss: 4.8875 - val_loss: 6.3823
Epoch 130/200
15/15 - 0s - 6ms/step - loss: 4.8841 - val_loss: 5.2549
Epoch 131/200
15/15 - 0s - 6ms/step - loss: 4.9236 - val_loss: 4.9225
Epoch 132/200
15/15 - 0s - 6ms/step - loss: 4.8176 - val_loss: 4.8483
Epoch 133/200
15/15 - 0s - 6ms/step - loss: 4.6077 - val_loss: 5.1306
Epoch 134/200
15/15 - 0s - 6ms/step - loss: 4.7919 - val_loss: 5.5416
Epoch 135/200
15/15 - 0s - 6ms/step - loss: 4.7917 - val_loss: 5.7390
Epoch 136/200
15/15 - 0s - 6ms/step - loss: 4.7639 - val_loss: 4.9289
Epoch 137/200
15/15 - 0s - 6ms/step - loss: 4.9911 - val_loss: 6.6421
Epoch 138/200
15/15 - 0s - 6ms/step - loss: 5.1902 - val_loss: 5.2514
Epoch 139/200
15/15 - 0s - 6ms/step - loss: 4.7852 - val_loss: 4.9294
Epoch 140/200
15/15 - 0s - 12ms/step - loss: 4.5816 - val_loss: 5.0147
Epoch 141/200
15/15 - 0s - 6ms/step - loss: 4.8165 - val_loss: 5.3507
Epoch 142/200
15/15 - 0s - 6ms/step - loss: 4.7814 - val_loss: 6.5484
Epoch 143/200
15/15 - 0s - 6ms/step - loss: 5.0718 - val_loss: 4.9491
Epoch 144/200
15/15 - 0s - 6ms/step - loss: 4.8071 - val_loss: 5.0428
Epoch 145/200
15/15 - 0s - 5ms/step - loss: 4.7663 - val_loss: 4.8851
Epoch 146/200
15/15 - 0s - 6ms/step - loss: 4.6822 - val_loss: 4.9140
Epoch 147/200
15/15 - 0s - 6ms/step - loss: 4.9272 - val_loss: 5.5411
Epoch 148/200
15/15 - 0s - 5ms/step - loss: 4.7963 - val_loss: 6.0081
Epoch 149/200
15/15 - 0s - 6ms/step - loss: 4.8447 - val_loss: 5.1245
Epoch 150/200
15/15 - 0s - 5ms/step - loss: 4.6687 - val_loss: 5.2336
Epoch 151/200
15/15 - 0s - 5ms/step - loss: 4.6956 - val_loss: 4.7724
Epoch 152/200
15/15 - 0s - 5ms/step - loss: 4.6764 - val_loss: 5.0384
Epoch 153/200
15/15 - 0s - 6ms/step - loss: 5.3898 - val_loss: 4.8473
Epoch 154/200
15/15 - 0s - 6ms/step - loss: 4.6196 - val_loss: 5.9058
Epoch 155/200
15/15 - 0s - 6ms/step - loss: 4.9721 - val_loss: 5.4841
Epoch 156/200
15/15 - 0s - 6ms/step - loss: 4.8030 - val_loss: 4.7388
Epoch 157/200
15/15 - 0s - 5ms/step - loss: 4.4797 - val_loss: 4.9994
Epoch 158/200
15/15 - 0s - 6ms/step - loss: 4.7228 - val_loss: 5.0775
Epoch 159/200
15/15 - 0s - 6ms/step - loss: 4.6900 - val_loss: 5.0379
Epoch 160/200
15/15 - 0s - 6ms/step - loss: 4.5815 - val_loss: 4.7595
Epoch 161/200
15/15 - 0s - 6ms/step - loss: 4.6145 - val_loss: 4.8846
Epoch 162/200
15/15 - 0s - 6ms/step - loss: 4.6357 - val_loss: 4.7238
Epoch 163/200
15/15 - 0s - 5ms/step - loss: 4.4944 - val_loss: 4.7634
Epoch 164/200
15/15 - 0s - 5ms/step - loss: 4.4581 - val_loss: 4.7944
Epoch 165/200
15/15 - 0s - 5ms/step - loss: 4.5774 - val_loss: 4.8742
Epoch 166/200
15/15 - 0s - 6ms/step - loss: 4.2512 - val_loss: 4.9035
Epoch 167/200
15/15 - 0s - 6ms/step - loss: 4.3890 - val_loss: 4.7315
Epoch 168/200
15/15 - 0s - 6ms/step - loss: 4.4919 - val_loss: 4.9515
Epoch 169/200
15/15 - 0s - 6ms/step - loss: 4.4062 - val_loss: 4.9379
Epoch 170/200
15/15 - 0s - 6ms/step - loss: 4.3636 - val_loss: 4.8577
Epoch 171/200
15/15 - 0s - 6ms/step - loss: 4.6487 - val_loss: 4.7325
Epoch 172/200
15/15 - 0s - 6ms/step - loss: 4.3697 - val_loss: 4.8480
Epoch 173/200
15/15 - 0s - 6ms/step - loss: 4.4910 - val_loss: 5.0920
Epoch 174/200
15/15 - 0s - 6ms/step - loss: 4.6021 - val_loss: 5.1054
Epoch 175/200
15/15 - 0s - 6ms/step - loss: 4.3766 - val_loss: 5.4563
Epoch 176/200
15/15 - 0s - 5ms/step - loss: 4.6661 - val_loss: 4.7792
Epoch 177/200
15/15 - 0s - 6ms/step - loss: 4.5082 - val_loss: 4.7689
Epoch 178/200
15/15 - 0s - 6ms/step - loss: 4.2584 - val_loss: 4.6221
Epoch 179/200
15/15 - 0s - 6ms/step - loss: 4.4172 - val_loss: 4.6352
Epoch 180/200
15/15 - 0s - 5ms/step - loss: 4.3434 - val_loss: 4.9742
Epoch 181/200
15/15 - 0s - 6ms/step - loss: 4.5875 - val_loss: 5.0778
Epoch 182/200
15/15 - 0s - 5ms/step - loss: 4.5710 - val_loss: 4.5838
Epoch 183/200
15/15 - 0s - 6ms/step - loss: 4.2828 - val_loss: 6.0852
Epoch 184/200
15/15 - 0s - 6ms/step - loss: 4.8807 - val_loss: 5.0923
Epoch 185/200
15/15 - 0s - 6ms/step - loss: 4.3516 - val_loss: 4.7171
Epoch 186/200
15/15 - 0s - 6ms/step - loss: 4.3368 - val_loss: 5.0954
Epoch 187/200
15/15 - 0s - 6ms/step - loss: 4.8840 - val_loss: 4.6565
Epoch 188/200
15/15 - 0s - 5ms/step - loss: 4.4544 - val_loss: 4.8647
Epoch 189/200
15/15 - 0s - 6ms/step - loss: 4.2321 - val_loss: 4.8073
Epoch 190/200
15/15 - 0s - 6ms/step - loss: 4.1070 - val_loss: 4.7139
Epoch 191/200
15/15 - 0s - 6ms/step - loss: 4.0993 - val_loss: 4.6882
Epoch 192/200
15/15 - 0s - 6ms/step - loss: 4.2642 - val_loss: 4.8579
Epoch 193/200
15/15 - 0s - 6ms/step - loss: 4.1645 - val_loss: 4.8000
Epoch 194/200
15/15 - 0s - 6ms/step - loss: 4.1824 - val_loss: 4.8700
Epoch 195/200
15/15 - 0s - 6ms/step - loss: 4.6142 - val_loss: 5.0567
Epoch 196/200
15/15 - 0s - 6ms/step - loss: 4.5017 - val_loss: 4.6007
Epoch 197/200
15/15 - 0s - 6ms/step - loss: 4.2023 - val_loss: 4.6190
Epoch 198/200
15/15 - 0s - 6ms/step - loss: 4.4078 - val_loss: 4.6672
Epoch 199/200
15/15 - 0s - 6ms/step - loss: 4.2341 - val_loss: 5.1412
Epoch 200/200
15/15 - 0s - 6ms/step - loss: 4.6194 - val_loss: 4.5528

In [17]:
model.evaluate(X,y)

33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 3.7741

3.774061918258667