In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data_raw = pd.read_csv("D:\\ML&DL\\heart.csv")
data = data_raw.copy()

In [3]:
data.replace({"Age":0 , "RestingBP":0 , "Cholesterol":0 , "MaxHR":0 },np.nan , inplace=True)

In [4]:
data.isna().sum()

Age                 0
Sex                 0
ChestPainType       0
RestingBP           1
Cholesterol       172
FastingBS           0
RestingECG          0
MaxHR               0
ExerciseAngina      0
Oldpeak             0
ST_Slope            0
HeartDisease        0
dtype: int64

In [5]:
data_categorical = data.select_dtypes("object")
data_numerical = data.select_dtypes(["float64" , "int64"]).iloc[:,:-1]
y = data.iloc[:,-1].values

In [6]:
from sklearn.preprocessing import LabelEncoder
label_enc = LabelEncoder()

In [7]:
data_categorical = data_categorical.apply(label_enc.fit_transform)

In [8]:
data_categorical.head()

   Sex  ChestPainType  RestingECG  ExerciseAngina  ST_Slope
0    1              1           1               0         2
1    0              2           1               0         1
2    1              1           2               0         2
3    0              0           1               1         1
4    1              2           1               0         2

In [9]:
data_categorical.nunique()

Sex               2
ChestPainType     4
RestingECG        3
ExerciseAngina    2
ST_Slope          3
dtype: int64

In [10]:
from sklearn.preprocessing import OneHotEncoder
ohe_enc = OneHotEncoder()

In [11]:
data_categorical_bin = data_categorical[["Sex","ExerciseAngina"]]

In [12]:
data_ohe = ohe_enc.fit_transform(data_categorical[["ChestPainType", "RestingECG" , "ST_Slope"]].values).toarray()

In [13]:
data_ohe.shape

(918, 10)

In [14]:
data = np.concatenate([data_numerical.values , data_categorical_bin.values , data_ohe], axis = 1)

In [15]:
pd.DataFrame(data)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,40.0,140.0,289.0,0.0,172.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1,49.0,160.0,180.0,0.0,156.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,37.0,130.0,283.0,0.0,98.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,48.0,138.0,214.0,0.0,108.0,1.5,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
4,54.0,150.0,195.0,0.0,122.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45.0,110.0,264.0,0.0,132.0,1.2,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
914,68.0,144.0,193.0,1.0,141.0,3.4,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
915,57.0,130.0,131.0,0.0,115.0,1.2,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
916,57.0,130.0,236.0,0.0,174.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
917,38.0,138.0,175.0,0.0,173.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [16]:
from sklearn.impute import KNNImputer

In [17]:
imputer = KNNImputer(n_neighbors=3)

In [18]:
data = imputer.fit_transform(data)

In [19]:

from sklearn.preprocessing import MinMaxScaler

In [20]:
scaler = MinMaxScaler()
data = scaler.fit_transform(data)

In [21]:
X = data

In [22]:
from sklearn.neighbors import KNeighborsClassifier

In [23]:
knn = KNeighborsClassifier()
knn.fit(X,y)

KNeighborsClassifier()

In [24]:
y_pred = knn.predict(X)

In [25]:
print(f"y true :  {y[:10]}")
print(f"y pred :  {y_pred[:10]}")

y true :  [0 1 0 1 0 0 0 0 1 0]
y pred :  [0 0 0 1 0 0 0 0 1 0]

In [26]:
from sklearn.metrics import accuracy_score

In [27]:
accuracy_score(y,y_pred)

0.8867102396514162

In [28]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X,y)

KNeighborsClassifier(n_neighbors=3)

In [29]:
y_pred = knn.predict(X)

In [30]:
accuracy_score(y,y_pred)

0.9084967320261438

Calssification Evalution

Slice Method

In [31]:
len(X[ : 600 , :])
len(y[ : 600])
y_train = y[: 600]
X_train = X[:600 , :]
y_test = y[600:]
X_test = X[600: , :]

In [32]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train , y_train)

KNeighborsClassifier()

In [33]:
y_pred = knn.predict(X_train)
acc_pred = accuracy_score(y_train,y_pred)
print(acc_pred)

0.92

In [34]:
y_pred = knn.predict(X_test)
acc_pred = accuracy_score(y_test , y_pred)
print(acc_pred)

0.7641509433962265

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_train , X_test , y_train , y_test = train_test_split(X , y , test_size=0.3 , random_state=1234)

In [37]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train , y_train)

KNeighborsClassifier()

In [38]:
y_pred = knn.predict(X_train)
acc_pred = accuracy_score(y_train,y_pred)
print(acc_pred)

0.881619937694704

In [39]:
y_pred = knn.predict(X_test)
acc_pred = accuracy_score(y_test , y_pred)
print(acc_pred)

0.8804347826086957

In [40]:
from sklearn import metrics

In [41]:
print(metrics.classification_report(y_test , y_pred))

              precision    recall  f1-score   support

           0       0.87      0.85      0.86       121
           1       0.89      0.90      0.89       155

    accuracy                           0.88       276
   macro avg       0.88      0.88      0.88       276
weighted avg       0.88      0.88      0.88       276

In [42]:
metrics.confusion_matrix(y_test , y_pred)

array([[103,  18],
       [ 15, 140]], dtype=int64)

Validation & Cross Validation

Using Validation for evaluate the classifier during the train proces.

In [43]:
from sklearn.model_selection import cross_validate

In [44]:
knn = KNeighborsClassifier(n_neighbors=7)
knn_valid = cross_validate(knn , X , y , cv=4 , scoring="accuracy" , verbose=10)

[CV] START .....................................................................
[CV] END ......................................., score=0.891 total time=   0.0s
[CV] START .....................................................................
[CV] END ......................................., score=0.857 total time=   0.0s
[CV] START .....................................................................
[CV] END ......................................., score=0.834 total time=   0.0s
[CV] START .....................................................................
[CV] END ......................................., score=0.742 total time=   0.0s

[Parallel(n_jobs=1)]: Done   1 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done   4 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done   4 out of   4 | elapsed:    0.0s finished

In [45]:
knn_valid

{'fit_time': array([0.00103092, 0.        , 0.        , 0.00199556]),
 'score_time': array([0.01496983, 0.01299834, 0.0150032 , 0.01300097]),
 'test_score': array([0.89130435, 0.85652174, 0.83406114, 0.74235808])}

In [46]:
knn_valid["test_score"]

array([0.89130435, 0.85652174, 0.83406114, 0.74235808])

In [47]:
knn_valid["test_score"].mean()

0.8310613252325803

In [48]:
knn_valid["test_score"].std

Now we are going to use the shufflesplit because of that in cross validate we have data compression then the randomness broking the work.

In [49]:
from sklearn.model_selection import ShuffleSplit

In [50]:
knn = KNeighborsClassifier(n_neighbors=7)
cv = ShuffleSplit(n_splits=5 , test_size=0.25 , random_state=1)
knn_valid = cross_validate(knn , X , y , cv=cv , scoring=["accuracy" , "f1"] , verbose=10 , return_train_score=True)

[CV] START .....................................................................
[CV] END  accuracy: (train=0.871, test=0.870) f1: (train=0.883, test=0.892) total time=   0.0s
[CV] START .....................................................................
[CV] END  accuracy: (train=0.884, test=0.857) f1: (train=0.900, test=0.855) total time=   0.0s
[CV] START .....................................................................
[CV] END  accuracy: (train=0.868, test=0.887) f1: (train=0.883, test=0.901) total time=   0.0s
[CV] START .....................................................................
[CV] END  accuracy: (train=0.879, test=0.848) f1: (train=0.893, test=0.869) total time=   0.0s
[CV] START .....................................................................
[CV] END  accuracy: (train=0.872, test=0.883) f1: (train=0.892, test=0.886) total time=   0.0s

[Parallel(n_jobs=1)]: Done   1 tasks      | elapsed:    0.0s
[Parallel(n_jobs=1)]: Done   4 tasks      | elapsed:    0.1s
[Parallel(n_jobs=1)]: Done   5 out of   5 | elapsed:    0.1s finished