In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
data = pd.read_csv("D:\ML&DL\outlier\data\data.csv")

In [3]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,anomaly
3,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [4]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,anomaly
3,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le = LabelEncoder()

In [7]:
for col in data.columns:
    if data[col].dtype == 'object':
        data[col] = le.fit_transform(data[col])

In [8]:
X = data.drop(columns=['class'])
y = data['class']

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler = StandardScaler()
X = scaler.fit_transform(X)

In [13]:
data['class'][data['class'] == 0] = -1

C:\Users\Ramin\AppData\Local\Temp\ipykernel_48436\4106188036.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['class'][data['class'] == 0] = -1

In [14]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,1,19,9,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,1
1,0,2,41,9,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,1
2,0,1,46,5,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,-1
3,0,1,22,9,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,1
4,0,1,22,9,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1

Using DBScan for detecting outlier data.

In [15]:
from sklearn.cluster import DBSCAN

In [16]:
model = DBSCAN()
model.fit(X)

DBSCAN()

In [17]:
y_pred = model.labels_

In [18]:
y_pred_index = set(np.where(y_pred == -1)[0])
y_true_index = set(np.where(data['class'] == -1)[0])
true_detection = y_pred_index.intersection(y_true_index)

In [19]:
hads_dorost = len(true_detection) / len(y_true_index)
hads_nadorost = (len(y_pred_index) - len(true_detection)) / (len(data) - len(y_true_index))

In [20]:
hads_dorost

0.06684833517840416

In [21]:
hads_nadorost

0.16239125585545394

Trying some kindes of hyper parameters for dbscan for realizing which condotion is better.

In [22]:
eps = [0.01 , 0.1 , 0.2 , 0.3 , 0.4 , 0.5 , 0.6 , 0.7 , 0.8 , 0.9 , 1 , 1.1 , 1.2 , 1.3]
n_samples = [3 , 5 , 10 , 20 , 50 , 100]
for e in eps:
    for n in n_samples:
        model = DBSCAN(eps=e , min_samples = n)
        model.fit(X)

        y_pred = model.labels_
        y_pred_index = set(np.where(y_pred == -1)[0])
        y_true_index = set(np.where(data['class'] == -1)[0])
        true_detection = y_pred_index.intersection(y_true_index)

        hads_dorost = len(true_detection) / len(y_true_index)
        hads_nadorost = (len(y_pred_index) - len(true_detection)) / (len(data) - len(y_true_index))


        print({"eps" : e , "n_samples" : n , "true_guess": hads_dorost , "false_guess" : hads_nadorost , "n_outlier":len(y_pred_index)})

{'eps': 0.01, 'n_samples': 3, 'true_guess': 0.9960827727156604, 'false_guess': 0.89895159491412, 'n_outlier': 23787}
{'eps': 0.01, 'n_samples': 5, 'true_guess': 0.9992335859661075, 'false_guess': 0.9263885790765113, 'n_outlier': 24193}
{'eps': 0.01, 'n_samples': 10, 'true_guess': 1.0, 'false_guess': 0.9520410439437876, 'n_outlier': 24547}
{'eps': 0.01, 'n_samples': 20, 'true_guess': 1.0, 'false_guess': 0.9709272064837534, 'n_outlier': 24801}
{'eps': 0.01, 'n_samples': 50, 'true_guess': 1.0, 'false_guess': 1.0, 'n_outlier': 25192}
{'eps': 0.01, 'n_samples': 100, 'true_guess': 1.0, 'false_guess': 1.0, 'n_outlier': 25192}
{'eps': 0.1, 'n_samples': 3, 'true_guess': 0.3094609554628289, 'false_guess': 0.5067291248419957, 'n_outlier': 10449}
{'eps': 0.1, 'n_samples': 5, 'true_guess': 0.4798603423316018, 'false_guess': 0.580117480853595, 'n_outlier': 13437}
{'eps': 0.1, 'n_samples': 10, 'true_guess': 0.7113173805671464, 'false_guess': 0.6401219421518328, 'n_outlier': 16962}
{'eps': 0.1, 'n_samples': 20, 'true_guess': 0.8617048454398365, 'false_guess': 0.7269685478474236, 'n_outlier': 19896}
{'eps': 0.1, 'n_samples': 50, 'true_guess': 0.9955718300263987, 'false_guess': 0.8622202394230054, 'n_outlier': 23287}
{'eps': 0.1, 'n_samples': 100, 'true_guess': 1.0, 'false_guess': 0.9040820878875753, 'n_outlier': 23902}
{'eps': 0.2, 'n_samples': 3, 'true_guess': 0.11249254875244827, 'false_guess': 0.290951000074355, 'n_outlier': 5234}
{'eps': 0.2, 'n_samples': 5, 'true_guess': 0.17499787107212808, 'false_guess': 0.35199643096140976, 'n_outlier': 6789}
{'eps': 0.2, 'n_samples': 10, 'true_guess': 0.27062931107894067, 'false_guess': 0.4506654769871366, 'n_outlier': 9239}
{'eps': 0.2, 'n_samples': 20, 'true_guess': 0.40117516818530186, 'false_guess': 0.5297048107665997, 'n_outlier': 11835}
{'eps': 0.2, 'n_samples': 50, 'true_guess': 0.6260751085753214, 'false_guess': 0.6382630678860882, 'n_outlier': 15936}
{'eps': 0.2, 'n_samples': 100, 'true_guess': 0.8061824065400665, 'false_guess': 0.7036954420403004, 'n_outlier': 18931}
{'eps': 0.3, 'n_samples': 3, 'true_guess': 0.0715319764966363, 'false_guess': 0.20209681017175998, 'n_outlier': 3558}
{'eps': 0.3, 'n_samples': 5, 'true_guess': 0.11436600527974113, 'false_guess': 0.2561528738196148, 'n_outlier': 4788}
{'eps': 0.3, 'n_samples': 10, 'true_guess': 0.18581282466150048, 'false_guess': 0.32916945497806527, 'n_outlier': 6609}
{'eps': 0.3, 'n_samples': 20, 'true_guess': 0.27863407987737376, 'false_guess': 0.413934121496022, 'n_outlier': 8839}
{'eps': 0.3, 'n_samples': 50, 'true_guess': 0.38550625904794344, 'false_guess': 0.5082162242545915, 'n_outlier': 11362}
{'eps': 0.3, 'n_samples': 100, 'true_guess': 0.4808822277101252, 'false_guess': 0.5806379656480035, 'n_outlier': 13456}
{'eps': 0.4, 'n_samples': 3, 'true_guess': 0.05271225410883079, 'false_guess': 0.15175849505539446, 'n_outlier': 2660}
{'eps': 0.4, 'n_samples': 5, 'true_guess': 0.08924465639104147, 'false_guess': 0.19733809205145364, 'n_outlier': 3702}
{'eps': 0.4, 'n_samples': 10, 'true_guess': 0.1377842118709018, 'false_guess': 0.26061417205740206, 'n_outlier': 5123}
{'eps': 0.4, 'n_samples': 20, 'true_guess': 0.20335519032615176, 'false_guess': 0.3344486578927801, 'n_outlier': 6886}
{'eps': 0.4, 'n_samples': 50, 'true_guess': 0.31039768372647536, 'false_guess': 0.43973529630455793, 'n_outlier': 9559}
{'eps': 0.4, 'n_samples': 100, 'true_guess': 0.3913820999744529, 'false_guess': 0.5095546137259276, 'n_outlier': 11449}
{'eps': 0.5, 'n_samples': 3, 'true_guess': 0.040960572255811976, 'false_guess': 0.11807569336010112, 'n_outlier': 2069}
{'eps': 0.5, 'n_samples': 5, 'true_guess': 0.06684833517840416, 'false_guess': 0.16239125585545394, 'n_outlier': 2969}
{'eps': 0.5, 'n_samples': 10, 'true_guess': 0.10789406454909307, 'false_guess': 0.21339876570748756, 'n_outlier': 4137}
{'eps': 0.5, 'n_samples': 20, 'true_guess': 0.17108064378778848, 'false_guess': 0.27392371180013386, 'n_outlier': 5693}
{'eps': 0.5, 'n_samples': 50, 'true_guess': 0.2666269266797241, 'false_guess': 0.3741542122090862, 'n_outlier': 8163}
{'eps': 0.5, 'n_samples': 100, 'true_guess': 0.32870646342501914, 'false_guess': 0.46568518105435347, 'n_outlier': 10123}
{'eps': 0.6, 'n_samples': 3, 'true_guess': 0.035936302478072044, 'false_guess': 0.0927206483753439, 'n_outlier': 1669}
{'eps': 0.6, 'n_samples': 5, 'true_guess': 0.05398961083198501, 'false_guess': 0.12848538924827124, 'n_outlier': 2362}
{'eps': 0.6, 'n_samples': 10, 'true_guess': 0.09086264157370348, 'false_guess': 0.1830619376905346, 'n_outlier': 3529}
{'eps': 0.6, 'n_samples': 20, 'true_guess': 0.14629992335859662, 'false_guess': 0.23325154286564057, 'n_outlier': 4855}
{'eps': 0.6, 'n_samples': 50, 'true_guess': 0.2352039512901303, 'false_guess': 0.3175700795598186, 'n_outlier': 7033}
{'eps': 0.6, 'n_samples': 100, 'true_guess': 0.2852763348377757, 'false_guess': 0.3985426425756562, 'n_outlier': 8710}
{'eps': 0.7, 'n_samples': 3, 'true_guess': 0.029038576173039257, 'false_guess': 0.07651126477805041, 'n_outlier': 1370}
{'eps': 0.7, 'n_samples': 5, 'true_guess': 0.04308950012773567, 'false_guess': 0.10721986764815228, 'n_outlier': 1948}
{'eps': 0.7, 'n_samples': 10, 'true_guess': 0.07672656050413013, 'false_guess': 0.1558480184400327, 'n_outlier': 2997}
{'eps': 0.7, 'n_samples': 20, 'true_guess': 0.12637315847739078, 'false_guess': 0.2058145587032493, 'n_outlier': 4252}
{'eps': 0.7, 'n_samples': 50, 'true_guess': 0.21399982968577025, 'false_guess': 0.27875678489107, 'n_outlier': 6262}
{'eps': 0.7, 'n_samples': 100, 'true_guess': 0.26083624286809165, 'false_guess': 0.3586883783180906, 'n_outlier': 7887}
{'eps': 0.8, 'n_samples': 3, 'true_guess': 0.02512134888869965, 'false_guess': 0.06513495427169307, 'n_outlier': 1171}
{'eps': 0.8, 'n_samples': 5, 'true_guess': 0.0356808311334412, 'false_guess': 0.0904899992564503, 'n_outlier': 1636}
{'eps': 0.8, 'n_samples': 10, 'true_guess': 0.06293110789406454, 'false_guess': 0.13294668748605845, 'n_outlier': 2527}
{'eps': 0.8, 'n_samples': 20, 'true_guess': 0.11581367623264924, 'false_guess': 0.18328500260242397, 'n_outlier': 3825}
{'eps': 0.8, 'n_samples': 50, 'true_guess': 0.193136336540918, 'false_guess': 0.24946092646293405, 'n_outlier': 5623}
{'eps': 0.8, 'n_samples': 100, 'true_guess': 0.2502767606233501, 'false_guess': 0.32336976726894195, 'n_outlier': 7288}
{'eps': 0.9, 'n_samples': 3, 'true_guess': 0.022566635442391212, 'false_guess': 0.056063647854859094, 'n_outlier': 1019}
{'eps': 0.9, 'n_samples': 5, 'true_guess': 0.0314229753895938, 'false_guess': 0.07844449401442487, 'n_outlier': 1424}
{'eps': 0.9, 'n_samples': 10, 'true_guess': 0.0502426977773993, 'false_guess': 0.11420923488735223, 'n_outlier': 2126}
{'eps': 0.9, 'n_samples': 20, 'true_guess': 0.09495018308779699, 'false_guess': 0.16268867573797308, 'n_outlier': 3303}
{'eps': 0.9, 'n_samples': 50, 'true_guess': 0.1739759856936047, 'false_guess': 0.22916201948100232, 'n_outlier': 5125}
{'eps': 0.9, 'n_samples': 100, 'true_guess': 0.23409690879672998, 'false_guess': 0.28567179715964014, 'n_outlier': 6591}
{'eps': 1, 'n_samples': 3, 'true_guess': 0.020267393340713615, 'false_guess': 0.048182020968101716, 'n_outlier': 886}
{'eps': 1, 'n_samples': 5, 'true_guess': 0.02725027676062335, 'false_guess': 0.06639898877239943, 'n_outlier': 1213}
{'eps': 1, 'n_samples': 10, 'true_guess': 0.04147151494507366, 'false_guess': 0.09904082087887575, 'n_outlier': 1819}
{'eps': 1, 'n_samples': 20, 'true_guess': 0.08055863067359278, 'false_guess': 0.14120008922596475, 'n_outlier': 2845}
{'eps': 1, 'n_samples': 50, 'true_guess': 0.16094694711743165, 'false_guess': 0.20878875752844078, 'n_outlier': 4698}
{'eps': 1, 'n_samples': 100, 'true_guess': 0.2199608277271566, 'false_guess': 0.24998141125734255, 'n_outlier': 5945}
{'eps': 1.1, 'n_samples': 3, 'true_guess': 0.01677595163075875, 'false_guess': 0.04282846308275708, 'n_outlier': 773}
{'eps': 1.1, 'n_samples': 5, 'true_guess': 0.023673677935791535, 'false_guess': 0.06022752621012715, 'n_outlier': 1088}
{'eps': 1.1, 'n_samples': 10, 'true_guess': 0.03704334497147237, 'false_guess': 0.08625176593055246, 'n_outlier': 1595}
{'eps': 1.1, 'n_samples': 20, 'true_guess': 0.06795537767180448, 'false_guess': 0.12506506059930106, 'n_outlier': 2480}
{'eps': 1.1, 'n_samples': 50, 'true_guess': 0.14212722472962616, 'false_guess': 0.185366941780058, 'n_outlier': 4162}
{'eps': 1.1, 'n_samples': 100, 'true_guess': 0.19219960827727156, 'false_guess': 0.23042605398170868, 'n_outlier': 5356}
{'eps': 1.2, 'n_samples': 3, 'true_guess': 0.01464702375883505, 'false_guess': 0.03769797010930181, 'n_outlier': 679}
{'eps': 1.2, 'n_samples': 5, 'true_guess': 0.020437707570467513, 'false_guess': 0.052197189382110196, 'n_outlier': 942}
{'eps': 1.2, 'n_samples': 10, 'true_guess': 0.03150813250447075, 'false_guess': 0.07837013904379508, 'n_outlier': 1424}
{'eps': 1.2, 'n_samples': 20, 'true_guess': 0.052371625649323, 'false_guess': 0.11130939103279054, 'n_outlier': 2112}
{'eps': 1.2, 'n_samples': 50, 'true_guess': 0.12730988674103721, 'false_guess': 0.16714997397576029, 'n_outlier': 3743}
{'eps': 1.2, 'n_samples': 100, 'true_guess': 0.1839393681342076, 'false_guess': 0.21771135400401517, 'n_outlier': 5088}
{'eps': 1.3, 'n_samples': 3, 'true_guess': 0.01302903857617304, 'false_guess': 0.03405457654844226, 'n_outlier': 611}
{'eps': 1.3, 'n_samples': 5, 'true_guess': 0.01839393681342076, 'false_guess': 0.045802661907948544, 'n_outlier': 832}
{'eps': 1.3, 'n_samples': 10, 'true_guess': 0.029208890402793154, 'false_guess': 0.07108335192207599, 'n_outlier': 1299}
{'eps': 1.3, 'n_samples': 20, 'true_guess': 0.04649578472281359, 'false_guess': 0.09881775596698639, 'n_outlier': 1875}
{'eps': 1.3, 'n_samples': 50, 'true_guess': 0.11436600527974113, 'false_guess': 0.15346865937987955, 'n_outlier': 3407}
{'eps': 1.3, 'n_samples': 100, 'true_guess': 0.17695648471429787, 'false_guess': 0.20380697449624507, 'n_outlier': 4819}