In [1]:
import pandas as pd
import numpy as np

For change the data time to an index.

In [2]:
data = pd.read_csv("D:\python-venv\RNN\data\climate dataset\climate.csv" ,  index_col='Date Time')

In [3]:
data.head()

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
Date Time,,,,,,,,,,,,,,
01.01.2009 00:10:00,996.52,-8.02,265.40,-8.90,93.3,3.33,3.11,0.22,1.94,3.12,1307.75,1.03,1.75,152.3
01.01.2009 00:20:00,996.57,-8.41,265.01,-9.28,93.4,3.23,3.02,0.21,1.89,3.03,1309.80,0.72,1.50,136.1
01.01.2009 00:30:00,996.53,-8.51,264.91,-9.31,93.9,3.21,3.01,0.20,1.88,3.02,1310.24,0.19,0.63,171.6
01.01.2009 00:40:00,996.51,-8.31,265.12,-9.07,94.2,3.26,3.07,0.19,1.92,3.08,1309.19,0.34,0.50,198.0
01.01.2009 00:50:00,996.51,-8.27,265.15,-9.04,94.1,3.27,3.08,0.19,1.92,3.09,1309.00,0.32,0.63,214.3

In [4]:
data.index

Index(['01.01.2009 00:10:00', '01.01.2009 00:20:00', '01.01.2009 00:30:00',
       '01.01.2009 00:40:00', '01.01.2009 00:50:00', '01.01.2009 01:00:00',
       '01.01.2009 01:10:00', '01.01.2009 01:20:00', '01.01.2009 01:30:00',
       '01.01.2009 01:40:00',
       ...
       '31.12.2016 22:30:00', '31.12.2016 22:40:00', '31.12.2016 22:50:00',
       '31.12.2016 23:00:00', '31.12.2016 23:10:00', '31.12.2016 23:20:00',
       '31.12.2016 23:30:00', '31.12.2016 23:40:00', '31.12.2016 23:50:00',
       '01.01.2017 00:00:00'],
      dtype='object', name='Date Time', length=420551)

Converting the string to date time. Datetime is string in daataset.

In [5]:
pd.to_datetime(data.index,format='%d.%m.%Y %H:%M:%S')

DatetimeIndex(['2009-01-01 00:10:00', '2009-01-01 00:20:00',
               '2009-01-01 00:30:00', '2009-01-01 00:40:00',
               '2009-01-01 00:50:00', '2009-01-01 01:00:00',
               '2009-01-01 01:10:00', '2009-01-01 01:20:00',
               '2009-01-01 01:30:00', '2009-01-01 01:40:00',
               ...
               '2016-12-31 22:30:00', '2016-12-31 22:40:00',
               '2016-12-31 22:50:00', '2016-12-31 23:00:00',
               '2016-12-31 23:10:00', '2016-12-31 23:20:00',
               '2016-12-31 23:30:00', '2016-12-31 23:40:00',
               '2016-12-31 23:50:00', '2017-01-01 00:00:00'],
              dtype='datetime64[ns]', name='Date Time', length=420551, freq=None)

In [6]:
data.index = pd.to_datetime(data.index,format='%d.%m.%Y %H:%M:%S')

We want to pick dataset every 3 hours for seq. Then set the min on 0 and hour to numbers that dividable to 3.

In [7]:
data = data[(data.index.minute == 0) & (data.index.hour % 3 == 0)]

In [8]:
data

,p (mbar),T (degC),Tpot (K),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
Date Time,,,,,,,,,,,,,,
2009-01-01 03:00:00,996.84,-8.81,264.59,-9.66,93.50,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
2009-01-01 06:00:00,997.71,-9.67,263.66,-10.62,92.70,2.93,2.71,0.21,1.69,2.72,1317.71,0.05,0.50,146.0
2009-01-01 09:00:00,999.69,-7.66,265.52,-8.84,91.20,3.43,3.13,0.30,1.95,3.13,1310.14,0.34,0.63,202.2
2009-01-01 12:00:00,1000.30,-6.87,266.27,-8.28,89.60,3.64,3.27,0.38,2.03,3.26,1306.98,1.84,2.63,184.4
2009-01-01 15:00:00,999.88,-5.69,267.48,-7.00,90.40,3.99,3.61,0.38,2.25,3.61,1300.51,1.17,1.88,134.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-31 12:00:00,1004.76,-1.19,271.60,-5.90,70.20,5.60,3.93,1.67,2.44,3.91,1285.09,0.86,1.56,211.2
2016-12-31 15:00:00,1003.12,5.09,278.00,-3.09,55.34,8.78,4.86,3.92,3.02,4.85,1253.58,0.30,0.70,134.1
2016-12-31 18:00:00,1002.27,-0.08,272.90,-4.90,69.81,6.07,4.24,1.83,2.64,4.23,1276.52,0.39,1.04,220.7
2016-12-31 21:00:00,1001.29,-3.09,269.98,-7.09,73.70,4.86,3.58,1.28,2.23,3.58,1289.78,0.61,1.48,207.5
2017-01-01 00:00:00,999.82,-4.82,268.36,-8.42,75.70,4.27,3.23,1.04,2.01,3.23,1296.38,1.23,1.96,184.9

In [9]:
tempc = data['T (degC)']
var = data.drop(columns=['T (degC)','Tpot (K)'])

In [10]:
var

,p (mbar),Tdew (degC),rh (%),VPmax (mbar),VPact (mbar),VPdef (mbar),sh (g/kg),H2OC (mmol/mol),rho (g/m**3),wv (m/s),max. wv (m/s),wd (deg)
Date Time,,,,,,,,,,,,
2009-01-01 03:00:00,996.84,-9.66,93.50,3.13,2.93,0.20,1.83,2.94,1312.18,0.18,0.63,167.2
2009-01-01 06:00:00,997.71,-10.62,92.70,2.93,2.71,0.21,1.69,2.72,1317.71,0.05,0.50,146.0
2009-01-01 09:00:00,999.69,-8.84,91.20,3.43,3.13,0.30,1.95,3.13,1310.14,0.34,0.63,202.2
2009-01-01 12:00:00,1000.30,-8.28,89.60,3.64,3.27,0.38,2.03,3.26,1306.98,1.84,2.63,184.4
2009-01-01 15:00:00,999.88,-7.00,90.40,3.99,3.61,0.38,2.25,3.61,1300.51,1.17,1.88,134.9
...,...,...,...,...,...,...,...,...,...,...,...,...
2016-12-31 12:00:00,1004.76,-5.90,70.20,5.60,3.93,1.67,2.44,3.91,1285.09,0.86,1.56,211.2
2016-12-31 15:00:00,1003.12,-3.09,55.34,8.78,4.86,3.92,3.02,4.85,1253.58,0.30,0.70,134.1
2016-12-31 18:00:00,1002.27,-4.90,69.81,6.07,4.24,1.83,2.64,4.23,1276.52,0.39,1.04,220.7
2016-12-31 21:00:00,1001.29,-7.09,73.70,4.86,3.58,1.28,2.23,3.58,1289.78,0.61,1.48,207.5
2017-01-01 00:00:00,999.82,-8.42,75.70,4.27,3.23,1.04,2.01,3.23,1296.38,1.23,1.96,184.9

Scaling the dataset.

In [11]:
from sklearn.preprocessing import StandardScaler

In [12]:
scaler = StandardScaler()
var = scaler.fit_transform(var)

In [13]:
var

array([[ 0.91270836, -2.17133967,  1.06222553, ..., -0.02326059,
        -0.02211692, -0.09183425],
       [ 1.01686391, -2.31396936,  1.0137245 , ..., -0.0252469 ,
        -0.02352123, -0.33721218],
       [ 1.25390756, -2.04951014,  0.92278507, ..., -0.0208159 ,
        -0.02211692,  0.31327082],
       ...,
       [ 1.56278262, -1.46413412, -0.37401116, ..., -0.02005194,
        -0.01768794,  0.52739779],
       [ 1.44545799, -1.7895081 , -0.13817491, ..., -0.01669049,
        -0.0129349 ,  0.3746153 ],
       [ 1.26947103, -1.98710965, -0.01692234, ..., -0.00721732,
        -0.00774976,  0.11303317]])

For 7 dayes and every day 8 seq we will have 56 seq.

Setting step=2 is going to jump one element in seq when want to start the next seq. In order seq one start from element 1 and end in 3. Seq 2 going to start form element 3 instate of element 2.

In [14]:
seq_len = 56
step = 2

In [15]:
sequences = []
targets = []

for i in range(0,len(data)-seq_len-7,step):
    seq = var[i:i+seq_len]
    target = tempc[i+seq_len+7]
    sequences.append(seq)
    targets.append(target)

sequences, targets = np.array(sequences), np.array(targets)

C:\Users\Ramin\AppData\Local\Temp\ipykernel_30280\3406242059.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  target = tempc[i+seq_len+7]

In [16]:
sequences.shape

(11650, 56, 12)

Because in time series we can not do the splitting random, then we do it manual with follow the order.

Train = 0.7 , Val = 0.2 , Test(final_test) = 0.1

In [17]:
X_train, X_val, X_test = sequences[:8155], sequences[8155:10485], sequences[10485:]
y_train, y_val, y_test = targets[:8155], targets[8155:10485], targets[10485:]

In [18]:
import tensorflow as tf
from tensorflow.keras.layers import GRU,Dense,Dropout
from tensorflow.keras.models import Sequential

In [19]:
model = Sequential()
model.add(GRU(units=128,activation='tanh',recurrent_dropout=0.2,input_shape=(56,12),return_sequences=True))
model.add(GRU(units=128,activation='tanh',recurrent_dropout=0.2,dropout=0.3))
model.add(Dropout(0.5))
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(1,activation='linear'))

d:\python-venv\keras2\lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [20]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ gru (GRU)                       │ (None, 56, 128)        │        54,528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ gru_1 (GRU)                     │ (None, 128)            │        99,072 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │        16,512 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 170,241 (665.00 KB)

 Trainable params: 170,241 (665.00 KB)

 Non-trainable params: 0 (0.00 B)

In [21]:
opt = tf.optimizers.Adam(learning_rate=0.001)
loss = tf.losses.MeanAbsoluteError()
model.compile(optimizer=opt,loss=loss)

In [22]:
model.fit(X_train,y_train,batch_size=50,epochs=40,validation_data=(X_val,y_val),verbose=2)

Epoch 1/40
164/164 - 22s - 134ms/step - loss: 4.4340 - val_loss: 2.7783
Epoch 2/40
164/164 - 10s - 58ms/step - loss: 3.1396 - val_loss: 2.5970
Epoch 3/40
164/164 - 9s - 54ms/step - loss: 3.0078 - val_loss: 2.6697
Epoch 4/40
164/164 - 9s - 54ms/step - loss: 3.0006 - val_loss: 2.5753
Epoch 5/40
164/164 - 9s - 52ms/step - loss: 2.9674 - val_loss: 2.5920
Epoch 6/40
164/164 - 9s - 54ms/step - loss: 2.9491 - val_loss: 2.5826
Epoch 7/40
164/164 - 9s - 55ms/step - loss: 2.8808 - val_loss: 2.6233
Epoch 8/40
164/164 - 11s - 69ms/step - loss: 2.9170 - val_loss: 2.5543
Epoch 9/40
164/164 - 27s - 165ms/step - loss: 2.8436 - val_loss: 2.5310
Epoch 10/40
164/164 - 42s - 257ms/step - loss: 2.8923 - val_loss: 2.5131
Epoch 11/40
164/164 - 40s - 247ms/step - loss: 2.8564 - val_loss: 2.5701
Epoch 12/40
164/164 - 22s - 136ms/step - loss: 2.8065 - val_loss: 2.5092
Epoch 13/40
164/164 - 23s - 142ms/step - loss: 2.8124 - val_loss: 2.5303
Epoch 14/40
164/164 - 28s - 169ms/step - loss: 2.8059 - val_loss: 2.4644
Epoch 15/40
164/164 - 27s - 167ms/step - loss: 2.8038 - val_loss: 2.4913
Epoch 16/40
164/164 - 41s - 248ms/step - loss: 2.8088 - val_loss: 2.4780
Epoch 17/40
164/164 - 42s - 253ms/step - loss: 2.7911 - val_loss: 2.4973
Epoch 18/40
164/164 - 27s - 166ms/step - loss: 2.7882 - val_loss: 2.4505
Epoch 19/40
164/164 - 27s - 163ms/step - loss: 2.7924 - val_loss: 2.4919
Epoch 20/40
164/164 - 44s - 269ms/step - loss: 2.7281 - val_loss: 2.5231
Epoch 21/40
164/164 - 31s - 187ms/step - loss: 2.7496 - val_loss: 2.4422
Epoch 22/40
164/164 - 29s - 179ms/step - loss: 2.7423 - val_loss: 2.4678
Epoch 23/40
164/164 - 41s - 248ms/step - loss: 2.7324 - val_loss: 2.4556
Epoch 24/40
164/164 - 40s - 242ms/step - loss: 2.7374 - val_loss: 2.4524
Epoch 25/40
164/164 - 41s - 249ms/step - loss: 2.6813 - val_loss: 2.5082
Epoch 26/40
164/164 - 31s - 190ms/step - loss: 2.7308 - val_loss: 2.4303
Epoch 27/40
164/164 - 39s - 238ms/step - loss: 2.6922 - val_loss: 2.4616
Epoch 28/40
164/164 - 31s - 187ms/step - loss: 2.6868 - val_loss: 2.4427
Epoch 29/40
164/164 - 38s - 230ms/step - loss: 2.6828 - val_loss: 2.4329
Epoch 30/40
164/164 - 27s - 166ms/step - loss: 2.6718 - val_loss: 2.4326
Epoch 31/40
164/164 - 27s - 162ms/step - loss: 2.6608 - val_loss: 2.4745
Epoch 32/40
164/164 - 18s - 109ms/step - loss: 2.6416 - val_loss: 2.4778
Epoch 33/40
164/164 - 23s - 140ms/step - loss: 2.6836 - val_loss: 2.4872
Epoch 34/40
164/164 - 29s - 176ms/step - loss: 2.6325 - val_loss: 2.4448
Epoch 35/40
164/164 - 28s - 173ms/step - loss: 2.6569 - val_loss: 2.4297
Epoch 36/40
164/164 - 28s - 169ms/step - loss: 2.6254 - val_loss: 2.4481
Epoch 37/40
164/164 - 27s - 166ms/step - loss: 2.5845 - val_loss: 2.4744
Epoch 38/40
164/164 - 41s - 250ms/step - loss: 2.5963 - val_loss: 2.4637
Epoch 39/40
164/164 - 10s - 64ms/step - loss: 2.6148 - val_loss: 2.5140
Epoch 40/40
164/164 - 9s - 53ms/step - loss: 2.6088 - val_loss: 2.4949

In [23]:
model.evaluate(X_test,y_test)

37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.1245

2.1245007514953613